name: Check PR format workflow

on:
  pull_request:
    types: [opened, reopened, edited]
    branches: [master]

jobs:
  gitlint:
    # Filter out Draft Pull Requests
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: python -m pip install gitlint==0.15.0
    - name: Run Gitlint
      run: python -c "import json; print(json.load(open('$GITHUB_EVENT_PATH'))['pull_request']['title'])" | gitlint
