name: Push workflow

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"

jobs:
  housekeeping:
    runs-on: ubuntu-latest
    container: qctrl/ci-images:python-3.11-ci
    steps:
      - uses: actions/checkout@v4
      - name: Download CI tool
        shell: bash
        run: |
          curl -sSL http://ci.q-ctrl.com | bash -
      - name: Vault Login
        run: |
          ./ci vault login -r ${{ secrets.VAULT_ROLE_ID }} -s ${{ secrets.VAULT_SECRET_ID }}
      - name: Perform housekeeping checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          /scripts/housekeeping.sh

  linting:
    runs-on: ubuntu-latest
    container: qctrl/ci-images:python-3.11-ci
    steps:
      - uses: actions/checkout@v4
      - name: Download CI tool
        shell: bash
        run: |
          curl -sSL http://ci.q-ctrl.com | bash -
      - name: Vault Login
        run: |
          ./ci vault login -r ${{ secrets.VAULT_ROLE_ID }} -s ${{ secrets.VAULT_SECRET_ID }}
      - name: Install Python dependencies
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          /scripts/install-python-dependencies.sh
      - name: Run Pre-Commit
        run: |
          poetry run pre-commit run -- -a

  pytest:
    runs-on: ubuntu-latest
    container: qctrl/ci-images:python-${{ matrix.python }}-ci
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Download CI tool
        shell: bash
        run: |
          curl -sSL http://ci.q-ctrl.com | bash -
      - name: Vault Login
        run: |
          ./ci vault login -r ${{ secrets.VAULT_ROLE_ID }} -s ${{ secrets.VAULT_SECRET_ID }}
      - name: Install Python dependencies
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          /scripts/install-python-dependencies.sh
      - name: Run Pytest
        run: |
          /scripts/pytest.sh

  publish_internally:
    runs-on: ubuntu-latest
    container: qctrl/ci-images:python-3.11-ci
    steps:
      - uses: actions/checkout@v4
      - name: Download CI tool
        shell: bash
        run: |
          curl -sSL http://ci.q-ctrl.com | bash -
      - name: Vault Login
        run: |
          ./ci vault login -r ${{ secrets.VAULT_ROLE_ID }} -s ${{ secrets.VAULT_SECRET_ID }}
      - name: Publish development version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          /scripts/publish-dev-version.sh
