name: Push workflow

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"

jobs:

  pre-checks:
    uses: qctrl/reusable-workflows/.github/workflows/poetry-pre-checks.yaml@master
    secrets: inherit

  pytest:
    uses: qctrl/reusable-workflows/.github/workflows/pytest.yaml@master
    secrets: inherit
    with:
      python-versions: '["3.9", "3.10", "3.11"]'

  publish:
    uses: qctrl/reusable-workflows/.github/workflows/poetry-publish-development.yaml@master
    secrets: inherit
