name: Release workflow

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    container: qctrl/ci-images:python-3.11-ci
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download CI tool
        shell: bash
        run: |
          curl -sSL http://ci.q-ctrl.com | bash -
      - name: Vault Login
        run: |
          ./ci vault login -r ${{ secrets.VAULT_ROLE_ID }} -s ${{ secrets.VAULT_SECRET_ID }}
      - name: Update version in code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          /scripts/housekeeping.sh
      - name: Publish publicly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          /scripts/publish-release-publicly.sh
      - name: Publish internally
        run: |
          /scripts/publish-release-internally.sh

  update_documentation:
    runs-on: ubuntu-latest
    container: qctrl/ci-images:python-3.11-ci
    steps:
      - name: Update docs repo
        uses: qctrl/reusable-workflows/.github/actions/docs/update-docs@master
        with:
          source_branch: master
          target_branch: master
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
