name: Release workflow

on:
  release:
    types: [published]

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update version in code
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        source <(curl -sL http://ci.q-ctrl.com)
        ./ci vault login -r ${{ secrets.VAULT_ROLE_ID }} -s ${{ secrets.VAULT_SECRET_ID }}
        ./ci docker run qctrl/python-build:3.7 /scripts/housekeeping.sh
    - name: Publish publicly
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        source <(curl -sL http://ci.q-ctrl.com)
        ./ci docker run qctrl/python-build:3.7 /scripts/publish-release-publicly.sh
    - name: Publish internally
      run: |
        ./ci docker run qctrl/python-build:3.7 /scripts/publish-release-internally.sh

  sphinx_documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Sphinx Image and Push to DockerHub
        run: |
          source <(curl -sL http://ci.q-ctrl.com)
          ./ci vault login -r ${{ secrets.VAULT_ROLE_ID }} -s ${{ secrets.VAULT_SECRET_ID }}
          ./ci vault get -t $(cat .token) -p secret/data/dockerhub -k hub_user -o .hub_user
          ./ci vault get -t $(cat .token) -p secret/data/dockerhub -k hub_pass -o .hub_pass
          ./ci docker buildPush \
            -f ./docs/Dockerfile \
            -u $(cat .hub_user) \
            -p $(cat .hub_pass) \
            --suffix -docs
      - name: Update Sphinx deployment in Kubernetes (Production)
        run: |
          ./ci vault login -r ${{ secrets.VAULT_ROLE_ID }} -s ${{ secrets.VAULT_SECRET_ID }}
          ./ci vault awsKey -t $(cat .token) -r deploy-eks-prod -o ./.aws-credentials
          ./ci docker run qctrl/ci-images:google-cloud-sdk-ci sh -- -c '
            . ./.aws-credentials;
            aws eks update-kubeconfig --alias hidden --name platform-prod --region us-west-2;
            kubectl -n qctrl-platform rollout restart deployment/python-open-controls-docs && kubectl -n qctrl-platform rollout status deployment/python-open-controls-docs;
          '
